# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('state_right', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('sort', models.PositiveSmallIntegerField(default=500, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'ordering': ['sort'],
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Question2UserTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'ordering': ['title'],
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='UserTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_done', models.BooleanField(default=False, verbose_name='Тест заврешоен')),
                ('passed_questions', models.ManyToManyField(through='base.Question2UserTesting', to='base.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат тестирования',
                'verbose_name_plural': 'Результаты тестирования',
            },
        ),
        migrations.AddField(
            model_name='question2usertesting',
            name='user_testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.UserTesting'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='base.Question', verbose_name='Вопрос'),
        ),
    ]
